# Generated by Django 3.2.7 on 2021-09-12 11:53

import car.services
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CarSubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.carmodel')),
            ],
        ),
        migrations.AddField(
            model_name='carmodel',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.make'),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(default=car.services.generate_hash, max_length=33, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('year', models.PositiveSmallIntegerField(verbose_name=django.core.validators.MinValueValidator(1886))),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField()),
                ('body_type', models.CharField(blank=True, max_length=100)),
                ('transmission', models.CharField(choices=[('automatic', 'automatic'), ('manual', 'manual')], default='automatic', max_length=9)),
                ('fuel_type', models.CharField(choices=[('diesel', 'diesel'), ('electricity', 'electricity'), ('hybrid', 'hybrid'), ('petrol', 'petrol')], max_length=11)),
                ('exterior_color', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carmodel')),
                ('submodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carsubmodel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('name', 'make')},
        ),
    ]
