# Generated by Django 3.2.7 on 2021-09-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='hash',
            field=models.CharField(max_length=33, unique=True),
        ),
    ]
