# Generated by Django 3.2.7 on 2021-09-12 14:34

import car.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='hash',
            field=models.CharField(default=car.services.generate_hash, max_length=33, unique=True),
        ),
    ]
