# Generated by Django 3.2.7 on 2021-09-13 05:16

import car.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20210912_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='hash',
            field=models.CharField(default=car.services.generate_hash, max_length=100, unique=True),
        ),
    ]
